name = "d1-northwind"
main = "dist/index.mjs"
workers_dev = true
compatibility_date = "2022-07-09"

[build]
command = "npm run build"
watch_dir = "worker"

[env.local]
[env.local.vars]
[[env.local.d1_databases]]
binding = "DB"
database_name = "d1-northwind"
database_id = "1"

[env.dev]
[env.dev.vars]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "d1-northwind-staging"
database_id = "41..."
[[env.dev.kv_namespaces]]
binding = "d1_northwind_assets"
id = "06..."

[env.production]
[env.production.vars]
[[env.production.d1_databases]]
binding = "DB"
database_name = "d1-northwind"
database_id = "c6..."
[[env.production.kv_namespaces]]
binding = "d1_northwind_assets"
id = "06..."

[[migrations]]
tag = "v1" # Should be unique for each entry

[[d1_databases]]
binding = "DB"
database_name = "d1-northwind"
database_id = "c6..."
